"""enrichment/threat_summary.py
----------------------------
Generates a threat summary report for a given IP address.
Saves reports inside enrichment/threat_reports/.
"""

import os
import json
from datetime import datetime, timezone
from typing import Any, Dict

from enrichment.abuseipdb import check_ip
from enrichment.geoip import get_geoip
from enrichment.virustotal import check_domain
from enrichment.risk_scorer import calculate_risk_score, get_risk_label

REPORTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "threat_reports")


def generate_threat_report(ip: str) -> Dict[str, Any]:
    """Generates a complete threat report for an IP address.

    Queries AbuseIPDB, GeoIP, and VirusTotal, calculates the risk score and risk
    level, and saves the report as JSON and Markdown inside
    enrichment/threat_reports/.

    Args:
        ip: The IP address to report on.

    Returns:
        A dictionary containing the compiled threat report.
    """
    os.makedirs(REPORTS_DIR, exist_ok=True)

    # 1. Fetch threat data
    try:
        geo = get_geoip(ip)
    except Exception:
        geo = {}

    try:
        abuse = check_ip(ip)
    except Exception:
        abuse = {}

    # Check VirusTotal (IP acts as domain check for mock consistency)
    try:
        vt = check_domain(ip)
    except Exception:
        vt = {"verdict": "CLEAN", "malicious_votes": 0, "harmless_votes": 70, "suspicious_votes": 0}

    # 2. Extract values
    country = geo.get("country") or geo.get("country_name") or abuse.get("country") or "Unknown"
    country_code = geo.get("country_code") or geo.get("countryCode") or abuse.get("country") or "Unknown"
    isp = geo.get("isp") or abuse.get("isp") or "Unknown ISP"
    abuse_score = abuse.get("abuse_score", 0)
    vt_verdict = vt.get("verdict", "CLEAN")
    vt_malicious = vt.get("malicious_votes", 0)
    vt_total = vt_malicious + vt.get("harmless_votes", 0) + vt.get("suspicious_votes", 0)

    # 3. Calculate Composite Score
    score_data = {
        "abuse_score": abuse_score,
        "vt_malicious": vt_malicious,
        "vt_total": vt_total if vt_total > 0 else 70,
        "geo_country_code": country_code,
    }
    risk_score = calculate_risk_score(score_data)
    risk_level = get_risk_label(risk_score)

    # 4. Determine Recommended Action
    if risk_level == "CRITICAL":
        recommended_action = "IMMEDIATE Containment: Isolate host, block IP on perimeter firewalls, terminate active user sessions, and initiate incident response playbook."
    elif risk_level == "HIGH":
        recommended_action = "Block IP: Configure firewall rules to block inbound and outbound traffic to this IP. Flag related user accounts for review."
    elif risk_level == "MEDIUM":
        recommended_action = "Monitor Closely: Add IP to active watchlists, correlate login logs, and inspect endpoint activity."
    else:
        recommended_action = "No Immediate Action: Low risk footprint. Log telemetry for future reference."

    timestamp = datetime.now(timezone.utc).isoformat()

    report = {
        "ip": ip,
        "country": country,
        "country_code": country_code,
        "isp": isp,
        "abuse_score": abuse_score,
        "virustotal_verdict": vt_verdict,
        "final_risk_score": risk_score,
        "risk_level": risk_level,
        "recommended_action": recommended_action,
        "timestamp": timestamp,
    }

    # Save as JSON
    json_path = os.path.join(REPORTS_DIR, f"report_{ip}.json")
    with open(json_path, "w", encoding="utf-8") as jf:
        json.dump(report, jf, indent=2)

    # Save as Markdown
    md_path = os.path.join(REPORTS_DIR, f"report_{ip}.md")
    md_content = f"""# SOARVault Threat Intelligence Report for IP: {ip}

Generated on: {timestamp}

## Overview

| Parameter | Value |
| :--- | :--- |
| **Target IP** | `{ip}` |
| **Country** | {country} ({country_code}) |
| **ISP** | {isp} |
| **AbuseIPDB Score** | {abuse_score}/100 |
| **VirusTotal Verdict** | {vt_verdict} (Malicious Votes: {vt_malicious}) |
| **Final Risk Score** | **{risk_score}/100** |
| **Risk Level** | **{risk_level}** |

## Recommended Containment Action

> **{recommended_action}**

---
*Generated by SOARVault Incident Containment Engine - Enrichment Module.*
"""
    with open(md_path, "w", encoding="utf-8") as mf:
        mf.write(md_content)

    return report
